// Code generated by hertz generator.

package main

import (
	handler "qnc/biz/handler"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// r.GET("/ws", handler.Ws, jwt.JwtMiddleware.MiddlewareFunc())
	r.GET("/ws", handler.Ws)

}
