// Code generated by hertz generator.

package image

import (
	"qnc/biz/mw/jwt"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _imageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _udMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _imageudMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		jwt.JwtMiddleware.MiddlewareFunc(),
	}
}
