INSERT INTO `qnc_kv` (`name`, `value`, `status`) VALUES ('deposit_1', '{ \"name\": \"10 Coins\", \"price\": \"0.99\", \"coin\": 10 }', 1);
INSERT INTO `qnc_kv` (`name`, `value`, `status`) VALUES ('deposit_2', '{ \"name\": \"30 Coins\", \"price\": \"2.97\", \"coin\": 30 }', 1);
INSERT INTO `qnc_kv` (`name`, `value`, `status`) VALUES ('deposit_3', '{ \"name\": \"50 Coins\", \"price\": \"4.90\", \"coin\": 50 }', 1);
INSERT INTO `qnc_kv` (`name`, `value`, `status`) VALUES ('deposit_4', '{ \"name\": \"100 Coins\", \"price\": \"9.88\", \"coin\": 100 }', 1);
INSERT INTO `qnc_kv` (`name`, `value`, `status`) VALUES ('payway_1', '{ \"name\": \"paypal\"}', 1);
INSERT INTO `qnc_kv` (`name`, `value`, `status`) VALUES ('payway_2', '{ \"name\": \"credit\"}', 1);
INSERT INTO `qnc_kv` (`name`, `value`, `status`) VALUES ('tips_1', 'Payment Notice', 1);


INSERT INTO `qnc_kv` (`name`, `value`, `status`) VALUES ('cloth_1', 'outfit', 1);
INSERT INTO `qnc_kv` (`name`, `value`, `status`) VALUES ('cloth_2', 'backless outfit', 1);
INSERT INTO `qnc_kv` (`name`, `value`, `status`) VALUES ('cloth_3', 'underboob cutout', 1);
INSERT INTO `qnc_kv` (`name`, `value`, `status`) VALUES ('cloth_4', 'shoulder cutout', 1);
INSERT INTO `qnc_kv` (`name`, `value`, `status`) VALUES ('cloth_5', 'sweater', 1);
INSERT INTO `qnc_kv` (`name`, `value`, `status`) VALUES ('cloth_6', 'off-shoulder sweater', 1);
INSERT INTO `qnc_kv` (`name`, `value`, `status`) VALUES ('cloth_7', 'halter dress', 1);
INSERT INTO `qnc_kv` (`name`, `value`, `status`) VALUES ('cloth_8', 'tank top', 1);
INSERT INTO `qnc_kv` (`name`, `value`, `status`) VALUES ('cloth_9', 'strapless leotard', 1);
INSERT INTO `qnc_kv` (`name`, `value`, `status`) VALUES ('cloth_10', 'leotard', 1);
INSERT INTO `qnc_kv` (`name`, `value`, `status`) VALUES ('cloth_11', 'sportswear', 1);
INSERT INTO `qnc_kv` (`name`, `value`, `status`) VALUES ('cloth_12', 'swimsuit', 1);
INSERT INTO `qnc_kv` (`name`, `value`, `status`) VALUES ('cloth_13', 'bikini', 1);
INSERT INTO `qnc_kv` (`name`, `value`, `status`) VALUES ('cloth_14', 'business suit', 1);
INSERT INTO `qnc_kv` (`name`, `value`, `status`) VALUES ('cloth_15', 'gothic_lolita', 1);
INSERT INTO `qnc_kv` (`name`, `value`, `status`) VALUES ('cloth_16', 'Maid dress', 1);
INSERT INTO `qnc_kv` (`name`, `value`, `status`) VALUES ('cloth_17', 'white_windbreaker', 1);
INSERT INTO `qnc_kv` (`name`, `value`, `status`) VALUES ('cloth_18', 'overcoat', 1);
INSERT INTO `qnc_kv` (`name`, `value`, `status`) VALUES ('cloth_19', 'coat', 1);
INSERT INTO `qnc_kv` (`name`, `value`, `status`) VALUES ('cloth_21', 'sweet_lolita', 1);
INSERT INTO `qnc_kv` (`name`, `value`, `status`) VALUES ('cloth_22', 'zentai', 1);
INSERT INTO `qnc_kv` (`name`, `value`, `status`) VALUES ('cloth_23', 'Raincoat', 1);
INSERT INTO `qnc_kv` (`name`, `value`, `status`) VALUES ('cloth_24', 'pajamas', 1);
INSERT INTO `qnc_kv` (`name`, `value`, `status`) VALUES ('cloth_25', 'sweatshirt', 1);
INSERT INTO `qnc_kv` (`name`, `value`, `status`) VALUES ('cloth_26', 'hoodie', 1);
INSERT INTO `qnc_kv` (`name`, `value`, `status`) VALUES ('cloth_27', 'Sailor Uniform', 1);
INSERT INTO `qnc_kv` (`name`, `value`, `status`) VALUES ('cloth_28', 'Soccer Jersey', 1);
