// Code generated by hertz generator.

package image

import (
	"context"

	"qnc/biz/model/image"
	service "qnc/biz/service/image"
	"qnc/pkg/utils"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// ImageUd .
// @router /image/ud/ [POST]
func ImageUd(ctx context.Context, c *app.RequestContext) {
	var err error
	var req image.ImageUdRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := service.NewImageService(ctx, c).ProcessImageUd(&req)
	if err != nil {
		resp := utils.BuildBaseResp(err)
		c.JSON(consts.StatusOK, image.ImageUdResponse{
			StatusCode: resp.StatusCode,
			StatusMsg:  resp.StatusMsg,
		})
		return
	}

	c.JSON(consts.StatusOK, resp)
}
