package router

import (
	"qnc/biz/router/api"
	"qnc/biz/router/image"
	"qnc/biz/router/pay"

	user "qnc/biz/router/user"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!

	user.Register(r)

	image.Register(r)
}

func GeneratedTopup(r *server.Hertz) {
	pay.Payment(r)
}

func ApiPayNotify(r *server.Hertz) {
	api.PayNotify(r)
}

func GetConf(r *server.Hertz) {
	api.GetDepositConf(r)

	api.GetClothes(r)
}
